/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author valery
 */
public class VistaBloques extends javax.swing.JPanel {

    /**
     * Creates new form VistaBloques
     */
    public VistaBloques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bloque2 = new javax.swing.JTextField();
        Bloque1 = new javax.swing.JTextField();
        Bloque0 = new javax.swing.JTextField();
        Bloque3 = new javax.swing.JTextField();
        Bloque4 = new javax.swing.JTextField();
        Bloque5 = new javax.swing.JTextField();
        Bloque6 = new javax.swing.JTextField();
        Bloque7 = new javax.swing.JTextField();
        Bloque8 = new javax.swing.JTextField();
        Bloque9 = new javax.swing.JTextField();
        Bloque10 = new javax.swing.JTextField();
        Bloque11 = new javax.swing.JTextField();
        Bloque12 = new javax.swing.JTextField();
        Bloque14 = new javax.swing.JTextField();
        Bloque15 = new javax.swing.JTextField();
        Bloque13 = new javax.swing.JTextField();
        Bloque16 = new javax.swing.JTextField();
        Bloque17 = new javax.swing.JTextField();
        Bloque18 = new javax.swing.JTextField();
        Bloque19 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Bloque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 40, 40));
        jPanel1.add(Bloque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 40, 40));

        Bloque0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque0ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        Bloque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque3ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 40, 40));

        Bloque4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque4ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 40, 40));
        jPanel1.add(Bloque5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 40, 40));
        jPanel1.add(Bloque6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 40, 40));

        Bloque7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque7ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 40, 40));

        Bloque8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque8ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, 40));
        jPanel1.add(Bloque9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 40, 40));
        jPanel1.add(Bloque10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 40, 40));

        Bloque11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque11ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, 40));

        Bloque12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque12ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 40));
        jPanel1.add(Bloque14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 40, 40));

        Bloque15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque15ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 40, 40));
        jPanel1.add(Bloque13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 40, 40));

        Bloque16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque16ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 40, 40));
        jPanel1.add(Bloque17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 40, 40));
        jPanel1.add(Bloque18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 40, 40));

        Bloque19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloque19ActionPerformed(evt);
            }
        });
        jPanel1.add(Bloque19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 40, 40));

        jLabel2.setText("3");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 10, -1));

        jLabel3.setText("0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 10, -1));

        jLabel4.setText("1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 10, -1));

        jLabel5.setText("2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 10, -1));

        jLabel6.setText("4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 10, -1));

        jLabel7.setText("5");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 10, -1));

        jLabel8.setText("6");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 10, -1));

        jLabel9.setText("7");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 10, -1));

        jLabel10.setText("9");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 10, -1));

        jLabel11.setText("11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 20, -1));

        jLabel12.setText("8");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 10, -1));

        jLabel13.setText("10");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 20, -1));

        jLabel14.setText("19");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 20, -1));

        jLabel15.setText("17");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 20, -1));

        jLabel16.setText("16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 20, -1));

        jLabel17.setText("18");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 20, -1));

        jLabel18.setText("15");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 20, -1));

        jLabel19.setText("14");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 20, -1));

        jLabel20.setText("12");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 20, -1));

        jLabel21.setText("13");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 20, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void Bloque0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque0ActionPerformed

    private void Bloque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque3ActionPerformed

    private void Bloque4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque4ActionPerformed

    private void Bloque7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque7ActionPerformed

    private void Bloque8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque8ActionPerformed

    private void Bloque11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque11ActionPerformed

    private void Bloque12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque12ActionPerformed

    private void Bloque15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque15ActionPerformed

    private void Bloque16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque16ActionPerformed

    private void Bloque19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloque19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bloque19ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bloque0;
    private javax.swing.JTextField Bloque1;
    private javax.swing.JTextField Bloque10;
    private javax.swing.JTextField Bloque11;
    private javax.swing.JTextField Bloque12;
    private javax.swing.JTextField Bloque13;
    private javax.swing.JTextField Bloque14;
    private javax.swing.JTextField Bloque15;
    private javax.swing.JTextField Bloque16;
    private javax.swing.JTextField Bloque17;
    private javax.swing.JTextField Bloque18;
    private javax.swing.JTextField Bloque19;
    private javax.swing.JTextField Bloque2;
    private javax.swing.JTextField Bloque3;
    private javax.swing.JTextField Bloque4;
    private javax.swing.JTextField Bloque5;
    private javax.swing.JTextField Bloque6;
    private javax.swing.JTextField Bloque7;
    private javax.swing.JTextField Bloque8;
    private javax.swing.JTextField Bloque9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
